### ISSUE TITLE
Error in mutate_impl(.data, dots) : found duplicated column name: NA

### ISSUE THREAD

**Issue by davidgasquez** [bufferapp/manual-payments#2]
Heya @jwinternheimer! Sorry to bother you again with yet another error. :sweat_smile: 

I've started to work on the manual payments Dockerfile after our learnings on the forecaster. The error I'm getting is related to the spreadsheet and hopefully is replicable¹! 

Seems there's a duplicate column in the spreadsheet that's being pulled into the dataframe but I'm not sure how to best ignore it and continue running the script.

```
Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Auto-refreshing stale OAuth token.
Sheet successfully identified: "Accounts Receivable - Checks, Invoices, Quotes"
Accessing worksheet titled 'Buffer Invoices'.
Parsed with column specification:
cols(
  .default = col_character()
)
See spec(...) for full column specifications.
Error in mutate_impl(.data, dots) : found duplicated column name: NA
Calls: main ... <Anonymous> -> mutate -> mutate.tbl_df -> mutate_impl
Execution halted
```

¹ If you wan't to run this locally, you'll need to have the latest code and place the secret (`googlesheets_token.rds`) under a `google` folder. Then a simple `make` will take care of building and running the script!

**Comment by jwinternheimer** [comment]
Thanks for the issue @davidgasquez! Should be fixed up here https://github.com/bufferapp/manual-payments/pull/3 😄

**Comment by davidgasquez** [comment]
Thanks for the quick PR @jwinternheimer! I've tried to run it again and I'm getting a different error, this time when copying to Redshift.

```
We did it.
[1] "The provided data.frame has 117 rows"
[1] "Uploading manual-payments/yxozmvueqficrjlp.0001"
[1] "Copying data from S3 into Redshift"
[1] "Failed to fetch row: ERROR:  Load into table 'ayejzxvcbguilhkn' failed.  Check 'stl_load_errors' system table for details.\n"
[1] "Deleting temporary files from S3 bucket"
[1] "Deleting yxozmvueqficrjlp.0001"
```
Checking `stl_load_errors` the table ([query](https://looker.buffer.com/sql/mhv6h8fbxhjsts)), seems the error is being caused by blank lines. :thinking:

**Comment by jwinternheimer** [comment]
Hmm, interesting @davidgasquez. Thanks for documenting! I'll have a look at it today, but I wasn't getting that error locally. Think we should open a new issue or reopen this one?

**Comment by davidgasquez** [comment]
Let's keep chatting on this one if it feels good!

**Comment by jwinternheimer** [comment]
This should be fixed in this PR https://github.com/bufferapp/manual-payments/pull/4 😄
